### ISSUE TITLE
Bitrate problem

### ISSUE THREAD

**Issue by Tester-helper** [philippe44/LMS-YouTube#13]
Hello Philippe, I have this problem with your plugin. I installed Logitech Media Server from the official website, on a fresh Windows 10 PRO. I activated 3rd party plugins, selected yours and I configured the connection to Youtube account. So finally I can see my playlists and I can listen to a lot of content, but only spoken words. I would like to hear also some music through my Squeezebox radio I have at home. The problem is that most of the songs I try to play, play only a few seconds. Then I see re-buffering on the screen, music starts after some pause and that repeats all the time. I discovered, that when I search in LMS for some low bittrate music, I can play it. So I guess the problem is that LMS gets from youtube too high bitrate which the wi-fi radio is not capable to process. Or I have something wrong set in the configuration. In fact I do not know where to look and what to set. But maybe there is something missing we could set in the plugin settings in LMS. Can you give me some advice or can that be fixed some way? Thank you for reading this! The plugin is, otherwise, very handy and the only of its kind I found and I would really like to use it fully. :)

**Comment by daumar** [comment]
I have the same issue. No idea what to do. Bigger NAS? Not sure

**Comment by Tester-helper** [comment]
I am running my LMS on Windows 10, 6 core, 16 gb ram daumar. So that is not about the hardware running the server in this case.

**Comment by philippe44** [comment]
Try a recent LMS version 7.9.2

**Comment by daumar** [comment]
Salue philippe,

I use 7.9.2
It worked very well for quite some time but now the buffering interrupts the replay of yt streams. Currently i have no further idea :-(

**Comment by Tester-helper** [comment]
Hi to you both ... Thanks both for the responses. So 7.7.6, my Windows LMS was older that is true. I thought I am downloading latest version from the official site. I did not give up, anyway, and I tried one more thing. I installed the LMS on my Raspberry Pi 2. Used Berry Boot on a flashidisk, which created a separate system, just for this. Made upgrade and install. There I got LMS 7.9.1 from some repository. On my Raspberry finally it works great for everything - so far. Not sure what is happening in W10 but daumar has newer version and still the same problem. So no clue, but on Raspbian everything ok at this moment, just I am sorry daumar you do not have your solution still. If any chance, try another device. Fixed for me, but I will watch the discussion if there will be a solution for daumar. :)

**Comment by daumar** [comment]
Hi Folks,
@Tester-helper thanks for your kind words! 

I am running a rather old Synology 213 with pretty low performance, 512mb ram and ARM5 processor only.

I now entirely removed the LMS package and did a reinstall from pinkdot using the package dedicated for my hardware. I followed this description. https://michaelsonntag.net/lms-7-9-2-auf-synology-nas-installieren/

What can I say. the system still says 7.9.2  (7.9.2 - 0018.1548605546) but seems to be a later build than I had on my device.

AND IT WORKS :-) tested exactly the stream that broke this morning. I am so happy now! 

best from Germany
Martin (aka daumar)

**Comment by Tester-helper** [comment]
Yay! I am happy for you Martin. So I can close the topic I guess. The plugin is very welcome. Would be fine to see similar things for more services. E.g. I am using bit.tube I guess it may not like Windows 10, but hard to say. Most important to me is, it works and since the start the Raspberry was meant as a final destination for my LMS, because it can run 24/7. Lets enjoy the music, take care! And thanks again for the good work philippe! :)
