### ISSUE TITLE
Youtube music does not start

### ISSUE THREAD

**Issue by crosenbe84** [philippe44/LMS-YouTube#14]
Hi all,

since a couple of weeks I do have an issue with playing music from youtube. The search is working fine, but I cannot play a song. According to LMS it is starting to play, but after 2-5 seconds it stops.
In the LMS server log following error is being listed:
[19-08-28 20:54:41.9409] Slim::Player::Song::open (410) Error: Couldn't create command line for ops playback for [youtube://www.youtube.com/v/2S7BvkDN0hw]

I'm using LMS version  7.9.2.
The youtube plugin version is v0.90.0, but above problem did already occur with the previous version.
The LMS is running on a Raspberry in conjunction with Max2Play.

Any idea on what might cause this issue? 

Thanks,
Christoph

**Comment by GAR2** [comment]
I have another problem - I can't play songs in the 48000 format. 44100 works fine.

**Comment by dixi83** [comment]
> I have another problem - I can't play songs in the 48000 format. 44100 works fine.
I have the same issue 44100 is playing but anything higher is not playing.
my log file is showing these errors:
```
[19-08-31 11:44:01.2039] Slim::Player::Song::open (409) Error: Couldn't create command line for ops playback for [youtube://www.youtube.com/v/9D2R69gVyZ0]
[19-08-31 11:44:02.3574] Plugins::YouTube::WebM::getTrackInfo (450) unknown codec V_VP8
```

**Comment by GAR2** [comment]
I resolved the problem by installing the newest version of LMS here:

http://downloads.slimdevices.com/nightly/?ver=7.9

**Comment by philippe44** [comment]
as said above, we have made a set of changes in LMS/squeezelite/YT to allow opus codec (which are always 48000) but you need to update all these components.

**Comment by dixi83** [comment]
Thanks. I upgraded to the latest nightly build as suggested bij GAR2. For me it is solved.

**Comment by crosenbe84** [comment]
Thanks for your hints - the plugin is working again!
