### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by NgTrThanh** [philippe44/LMS-YouTube#16]
Hi
I just installed LMS on NAS server, 
Play other thing including online Tidal/offline files OK
Set up everything with 
YouTube API access key:OK
Searching OK
Play OK, but no sound output?

**Comment by philippe44** [comment]
Please ask the question on LMS forum https://forums.slimdevices.com/showthread.php?105840-ANNOUNCE-YouTube-Plugin-(API-v3)
