### ISSUE TITLE
Youtube Radio 24/24 ne se joue pas

### ISSUE THREAD

**Issue by ludisnet** [philippe44/LMS-YouTube#19]
Bonjour,

Apparement, les radios youtube 24/24 ne se lance pas, est-ce normal, est-il possible de prendre en charge ? 
Ex: https://youtu.be/5qky3L2Q6G4

Merci. 

Ludis

**Comment by philippe44** [comment]
Works for me

**Comment by ludisnet** [comment]
does not work for me, the other youtube yes, but not the radios 24/24 like the link sent, the playing starts, the time goes by, but no sound ...
how can i solve ? a log to provide?

**Comment by philippe44** [comment]
What version of the YT plugin do you have? Set the YT plugin log to "info" and send me a log

**Comment by ludisnet** [comment]
Version oy YT plugin is 0.100.0.
Player is various but for example :  Silvercrest multiroom wifi DLNA(upnp) (https://www.silvercrest-multiroom.de/fr/produits/enceinte-wifi-18-w/)

Where Set (and download) the log of plugin ?

Thanks you

Ludis

**Comment by philippe44** [comment]
Settings/Advanced/Logging/ search for plugin.youtube and set it to "info" then take the server.log in Settings/Information (at the bottom of the page)

**Comment by ludisnet** [comment]
I'm sending the logs over tonight....

I don't have a SB device (..squeezeBox ?) ....
I use also Softsqueeze on windows, with same issue , he should support aac .... (http://softsqueeze.sourceforge.net/)

Thanks

Ludis

**Comment by philippe44** [comment]
You really have to be careful with aac support, because again it's very diverse. I really recommend you to disable aac codec in whatever client you use to force LMS to transcode and see if it still does not work

**Comment by ludisnet** [comment]
So, is it ok , .... on remove codec aac in commun parameters of upnpbridge, and activate transcode mp3. is-it a good way ?

Many thanks for support.
Ludis

**Comment by philippe44** [comment]
These are 2 separated things

- remove aac from "supported codecs" will force the UPnPBridge to tell LMS that the UPnP player does not support aac, so LMS will have to transcode anything aac *at the server level* to the most suitable codec in the list.

- transcode mode, in the context of the UPnPBridge is the fact that the bridge will decode all incoming audio *from* LMS (using the listed "supported codecs") and then re-encode it using flac,mp3 or use plain pcm to send it *to* the UPnP player. But the format *to* the UPnP Player is independent from what you tell LMS is supported. Extreme example; you can tell LMS that only mp3 is supported by the bridge and then configure the bridge to re-encode that received mp3 to flac before sending that to the UPnP device

One of reason for the second mode is to have a well controller audio format sent to the UPnP player as they can be very picky about that and in passthrough mode, they receive whatever LMS sends (and in case of live stream, it even whatever LMS receives)

Think about the bridge as ... a bridge that creates fake Squeezeboxes and make LMS believe that it is talking to a real SB. The bridge can simply translate the commands (play/pause ...) and pass the audio through or it can as well translate (transcode) it. This requires more CPU but

**Comment by ludisnet** [comment]
Hello,

works well by removing aac ... without transcode.

Thank you very much for the explanations and well done for what you are doing.

Good continuation.

best regards.

Ludis
