### ISSUE TITLE
How to use doesn't match between plugin and forum

### ISSUE THREAD

**Issue by Yogui79** [philippe44/LMS-YouTube#20]
Hello
first of all thank for this plugin.
the how to use doesn't match between the pluging configuration inside LMS(not working for me) and what you describe on the forum website(works for me). see attach screen 

LMS
![Capture-20200430143915-841x131](https://user-images.githubusercontent.com/8452608/80711687-0d1d5900-8af1-11ea-8141-2ab0757c10e4.png)

Forum
![Capture-20200430143957-790x357](https://user-images.githubusercontent.com/8452608/80711689-0db5ef80-8af1-11ea-8f48-468cecc5dafa.png)

thanks

**Comment by philippe44** [comment]
These are different things

**Comment by philippe44** [comment]
Closed for inactivity

**Comment by Yogui79** [comment]
> These are different things
sorry for my bad interpretation, but this is very confusing

**Comment by philippe44** [comment]
You have 2 set of credentials 
1- the API key which is a general purpose access to YT services
2- The Oauth key which is needed to access your personal account
