### ISSUE TITLE
Better error message when trying to play vorbis/opus stream

### ISSUE THREAD

**Issue by alexanderadam** [philippe44/LMS-YouTube#24]
I'm not quite sure whether this is possible, but I ran into the vorbis/opus issue and the Squeezebox just showed `problem: unable to play file type for $youtube_title`. It didn't even show anything about "vorbis" or "opus".
I had to look in the LMS log to find `Slim::Player::Song::open (409) Error: Couldn't create command line for ops playback for [youtube://www.youtube.com/v/…` and thus finding the reason.

So I guess it would be great if the error message could be improved.

Apart from that the plugin is working flawlessly for me, so **thank you so much for maintaining it and your work on LSM things in general**! :pray: 
Your work is really outstanding!

**PS:** Do you know what could be missing when this error occurs? I'm using [@**apnar**](https://github.com/apnar/docker-image-logitech-media-server)'s Docker image [and I thought that all required dependencies should be available](https://github.com/apnar/docker-image-logitech-media-server/blob/cef744fd19eebfe44f5d5103b84e59a14f1141a0/Dockerfile#L12-L15)?

**Comment by philippe44** [comment]
Thank you :-)

That error should not occur - can you send me an URL when it happens?

**Comment by alexanderadam** [comment]
I have to thank _you_, Philippe! :wink: 
It happens on _every_ YouTube URL for me as long `vorbis/opus` is activated. I'm not the only one as I saw others having the same problem in the Forum and some mailing lists.
Can I give you some data or log helping you to debug this?

**Comment by philippe44** [comment]
Have you tried version 0.110.2? I've just uploaded 0.120 and integrated a PR which seems to have broken things, but AFAIK, vorbis/opus works for me on every single track on 0.110.2

**Comment by philippe44** [comment]
I missed the initial comment. I think one of of the transcoder is missing in your setup, seems to be sox. What player are you using? You should try to set "player.source" logging to debug and see what's being spit out.

**Comment by alexanderadam** [comment]
> I missed the initial comment. I think one of of the transcoder is missing in your setup, seems to be sox. What player are you using? You should try to set "player.source" logging to debug and see what's being spit out.

[`sox` is installed in the image](https://github.com/apnar/docker-image-logitech-media-server/blob/cef744fd19eebfe44f5d5103b84e59a14f1141a0/Dockerfile#L12-L15) and these are the specs of the player that I use:

Player Model: `Squeezebox Radio`
Player Type: `baby`
Firmware: `7.7.3-r16676`
The plugin has version `v0.110.2`

I increased logging but the error stays the same:

```
Slim::Player::Song::open (409) Error: Couldn't create command line for ops playback for [youtube://www.youtube.com/v/GKSRyLdjsPA]
```

**Comment by philippe44** [comment]
Very strange - what are your convert.conf and custom-convert.conf? I'm hesitating with the README prt that talks about opus/vorbis as I think this is specific to a problem with your configuration

**Comment by alexanderadam** [comment]
I never touched those files and I don't think they're modified [in the rest of the simple Docker setup](https://github.com/apnar/docker-image-logitech-media-server/).

However, I just saw that I was using an older LMS release (`7.x`). I just updated to `8` and now everything is working again.
I'm so sorry Philippe! :see_no_evil: 

> I'm hesitating with the README because that talks about opus/vorbis as I think this is specific to a problem with your configuration

The setup doesn't change anything regarding codecs.

Also this seem to happen in other cases as well (this is why I found out that disabling vorbis works).
See [this forum entry of the user Squid](https://forums.slimdevices.com/archive/index.php/t-105840-p-3.html#:~:text=If%20I%20only%20enable%20AAC%20and%20disable%20Vorbis,%20it%20is%20working%20fine) or [this GitHub comment](https://github.com/philippe44/LMS-YouTube/issues/14#issuecomment-526817723).

They might have had different causes but you can't have problems with vorbis logic if you disabled it, right? :wink: 
Furthermore it solved to problem.

However, I just removed the part with the solution now.

**Comment by philippe44** [comment]
There was indeed a problem with vorbis/opus but that was a while ago and I corrected it, hence I was confused. You absolutely can remove opus/vorbis support but these are good, modern, codecs and I donc know how much YT will support aac in the future. They already have abandoned codecs in the past and the trend for them really seems to be opus
