### ISSUE TITLE
no stream/DASH found 

### ISSUE THREAD

**Issue by kiss81** [philippe44/LMS-YouTube#28]
First of all this plugin is fantastic for the streams that work. It's so fast! Unfortunately on every (copyrighted?) "song" does give me this error, while some other vlog streams seem to work.
I run LMS 7.9.3 on picoreplayer. When I enable logging on the not working streams I see:
Plugins::YouTube::ProtocolHandler::__ANON__ (422) no stream/DASH found

**Comment by philippe44** [comment]
see forum

**Comment by kiss81** [comment]
For info here: clear the LMS cache is the solution. I can confirm this worked .Thanks for the fast "fix".
