### ISSUE TITLE
Sanity checking required - got tens of thousands of errors in server.log

### ISSUE THREAD

**Issue by michaelherger** [philippe44/LMS-YouTube#29]
https://github.com/philippe44/LMS-YouTube/blob/718bd0b9747e57190b746d61fbd19bbc7ae6cc2b/plugin/ProtocolHandler.pm#L263

`$props->{'segmentURL'}` fails to be an ARRAY ref under whatever circumstances. Please make sure it is what you expect it to be. `sysread` is called often, creating quite some noise...

**Comment by philippe44** [comment]
Updated in 0.125.0
