### ISSUE TITLE
Could not find JS function 'Zq'

### ISSUE THREAD

**Issue by tomscytale** [philippe44/LMS-YouTube#3]
some time in the last 24 hours some youtube videos no longer play using the plugin. 
on my squeezebox touch screen i see the message:

`cannot load player code: Could not find JS function 'Zq' at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/YouTube/JSInterp.pm line 394.`

youtube url: https://www.youtube.com/watch?v=rNMevNpavlY

Logitech Media Server Version: 7.9.0 - 1415230120 @ Thu Nov 6 03:56:16 UTC 2014
Operating system: Debian - EN - utf8
Platform Architecture: i686-linux
Perl Version: 5.20.1 - i686-linux-gnu-thread-multi-64int

Player Model: Squeezebox Touch
Player Type: fab4
Firmware: 7.8.0-r16754

**Comment by philippe44** [comment]
I just made a patch for that but I'm not sure that this is really the proper solution (it works, though). I've asked the opinion of original developer of this piece
