### ISSUE TITLE
Playing a saved playlist doesn't always work reliable

### ISSUE THREAD

**Issue by Gagi2k** [philippe44/LMS-YouTube#30]
Hi,

thx for your great plugin. I noticed the following Problem.

I have created a Youtube Playlist of a few pretty long videos and saved them in my account and also saved this as a Favorite in the LMS.
Now if go to the Youtube Plugin, to the saved Playlists and want to play the whole Playlist, sometimes it doesn't load all tracks. If that happens i can clear the current playqueue and try to play the playlist again, but nothing happens.

When i browse into the playlist and just select one track it asks me whether i want to play from the start or where i stopped last. Once i select something there it starts playing. Clear the playqueue again and try to add the whole playlist. This time it just adds the Video which i just played, but no other video.

Listing to the LMS notifications using telnet i get the following:

dc%3A44%3A6d%3Acb%3Acf%3Aae power 0
dc%3A44%3A6d%3Acb%3Acf%3Aae prefset server power 0
dc%3A44%3A6d%3Acb%3Acf%3Aae menustatus ARRAY(0x55e99f063e98) add dc%3A44%3A6d%3Acb%3Acf%3Aae
dc%3A44%3A6d%3Acb%3Acf%3Aae playlist loadtracks listref ARRAY(0x55e99f3ce948)   index%3A0
dc%3A44%3A6d%3Acb%3Acf%3Aae playlist stop
dc%3A44%3A6d%3Acb%3Acf%3Aae playlist jump
dc%3A44%3A6d%3Acb%3Acf%3Aae power 1 1
dc%3A44%3A6d%3Acb%3Acf%3Aae prefset server power 1
dc%3A44%3A6d%3Acb%3Acf%3Aae menustatus ARRAY(0x55e99f4905f0) add dc%3A44%3A6d%3Acb%3Acf%3Aae
dc%3A44%3A6d%3Acb%3Acf%3Aae newmetadata
dc%3A44%3A6d%3Acb%3Acf%3Aae playlist open youtube%3A%2F%2Fwww.youtube.com%2Fv%2FxoeTL50KzI8
dc%3A44%3A6d%3Acb%3Acf%3Aae playlist open youtube%3A%2F%2Fwww.youtube.com%2Fv%2FxoeTL50KzI8
dc%3A44%3A6d%3Acb%3Acf%3Aae playlist newsong Vom%20Anfang%20an%20wiedergeben 0

What i want to be able to at the end is to play the playlist (from start) using the LMS favorites, but also over the CLI by using the stored playlist URL (from the LMS favorites)

**Comment by philippe44** [comment]
For clarification: are these playlists created in YouTube (i.e. can you find them on your YT account) or in LMS?

**Comment by Gagi2k** [comment]
They were created on the YT account and are Youtube Playlists

**Comment by philippe44** [comment]
That has been solved, it was only for the already played tracks
