### ISSUE TITLE
no stream/DASH found

### ISSUE THREAD

**Issue by fsquillace** [philippe44/LMS-YouTube#31]
Hi,

Thanks for making this plugin, it is very cool!

It all the sudden stopped working. I keep getting the following lines every time I attempt to play a YT video in LSM:

```
[21-03-31 00:48:28.3306] Plugins::YouTube::ProtocolHandler::__ANON__ (448) no stream/DASH found
[21-03-31 00:48:28.8216] Plugins::YouTube::ProtocolHandler::__ANON__ (448) no stream/DASH found

```

I tried create a new project  with new creds but no luck.

Youtube plugin version is 0.127.1

Do you have any clue on how to fix this?

**Comment by sanghoku** [comment]
Same here:
- Server running on a raspberry pi
- YT plugin worked good on tuesday (2 days ago)
- Now it doesn't
- It has account access (history, subscriptions, search works, thumbnails, etc)
- playing displays on my Radio something that roughly translates to "can't find track"
- logs show the text for the Google policies popup "before you continue to YouTube...", like you see when not logged in to YT
- Don't know how to "accept" these on CLI

**Comment by sanghoku** [comment]
VLC (3.0.12) also stopped playing youtube streams btw

**Comment by sanghoku** [comment]
This works in VLc, so how to do this in the YT plugin?
Tools -> Preferences -> Show settings: All -> Input/Codecs -> Access modules -> HTTPS -> uncheck Cookies forwarding

**Comment by labor4** [comment]
Had the same error
- tried to find the plugin in the PluginPage, couldn't find
- installed Philippe's dev repo, server updated something on its own
- Youtube Plugin (Philippe) visible and active with v0.140.1
...works again. Server log looks sober. 
Don't know what that's telling, or at what version it got fixed.
