### ISSUE TITLE
LMS Cli support?

### ISSUE THREAD

**Issue by hansmorb** [philippe44/LMS-YouTube#33]
Hey, 

I was asking if there is a possibility to control the Youtube Plugin over LMS-Cli (https://github.com/elParaguayo/LMS-CLI-Documentation/blob/master/LMS-CLI.md). This would be really awesome.

Thank you.

**Comment by philippe44** [comment]
No, that would be a lengthy interface if you want to add all search option. But maybe one day. I'm just too busy currently
