### ISSUE TITLE
Error : No player url to unobfuscate signature

### ISSUE THREAD

**Issue by Duc** [philippe44/LMS-YouTube#34]
Hi philippe44,

When I tried to play this [youtube file](https://www.youtube.com/watch?v=YdW5-uJqCVY) get this error message :

`Plugins::YouTube::ProtocolHandler::getSignature (786) no player url to unobfuscate signature`

I successfully play AAC file but not the Youtube Format file. My setup is : 
* sox (14.4.2+git20190427-1) 
* Logitech Media Server (v8.1.1), tested with version 8.2, same issue.
* Raspberry armv7l running Debian buster.
* The plug-in version is 0.140.1

I cannot determine if it's codec related but I used to play this file often without any issue on the same computers.

Hope you can point me the right direction. Regards.

**Comment by sanghoku** [comment]
See also forum where same error was logged:
https://forums.slimdevices.com/showthread.php?105840-ANNOUNCE-YouTube-Plugin-(API-v3)&p=1026121&viewfull=1#post1026121

**Comment by Duc** [comment]
Thanks @sanghoku  for the reply.

I read all the thread but I cannot find a solution. It seems I am not alone on this issue. I thinkt it's related to vorbis/opus codec.

**Comment by Duc** [comment]
Fixed with the update to the version 0.140.2 of the plugin.
