### ISSUE TITLE
Stopped working. Cannot play Youtube Sound any more 

### ISSUE THREAD

**Issue by ruedigerkupper** [philippe44/LMS-YouTube#37]
All keys and secrets are unchanged. Still, this app does not work any longer. Always returns an empty list.

**Comment by hipernet** [comment]
I have same problem ?

**Comment by philippe44** [comment]
Probably should delete the whole project and create a new one

**Comment by hipernet** [comment]
no effect

**Comment by hipernet** [comment]
Get code , Refresh no

**Comment by philippe44** [comment]
Is this a key issue or just the oauth with personal playlist access?

**Comment by hipernet** [comment]
OAuth TV  start work , thanks
