### ISSUE TITLE
LMS-Youtube on MAC OS X EL Capitan 10.11.1

### ISSUE THREAD

**Issue by lmsyoutube** [philippe44/LMS-YouTube#4]
After installation the is an error saying "Missing Youtube API Key (see settings)"
What do we do now?

**Comment by philippe44** [comment]
Look at the settings, as explained, and it will tell you what you need to get a YouTube API key. This is

**Comment by philippe44** [comment]
Go to LMS 'settings' pages then choose 'advanced' tab and in the dropdown list (on the left) choose YouTube. This will open the YouTube plugin settings where you ahve more explanations

**Comment by lmsyoutube** [comment]
Thank you Philippe
Works now ok
