### ISSUE TITLE
sources for 0.144.2

### ISSUE THREAD

**Issue by tmancill** [philippe44/LMS-YouTube#42]
Hello @philippe44  - thank you for continuing to maintain this LMS plugin.  My question is regarding where to pull the latest sources.  In this repo, I see 0.144.1, but within LMS the installed version of the plugin is 0.144.2, and the `InstalledPlugins/Plugins/YouTube/CHANGELOG` is newer than what is currently in [CHANGELOG](https://github.com/philippe44/LMS-YouTube/blob/master/CHANGELOG):

```
0.144.2
 - update CZ transation
 - fix JS signature
```

I can copy from the installed plugin back to my fork, but I wanted to ask if there is a different upstream repo for the latest sources, pull-requests, etc.

**Comment by philippe44** [comment]
No, I just forgot to push the latest package
