### ISSUE TITLE
On-disk caching

### ISSUE THREAD

**Issue by seidler2547** [philippe44/LMS-YouTube#43]
Hi, is there a way to cache the played music locally? We use the plugin extensively in our family and a lot of songs get played very often. I think sometimes the YouTube API is then overwhelmed and it's not working for a while and then starts working again after some time or with another song. It would be great if the stream could be saved locally to disk so that it won't be fetched over and over again.

**Comment by philippe44** [comment]
No, I’ve done something similar as a general LMS feature for http flows but it only serves the purpose of better handling streaming connectivity issues. Recording YT is a very controversial topic which caused ytdl site to have been suspended and triggered a long legal battle…
