### ISSUE TITLE
no stream/DASH found

### ISSUE THREAD

**Issue by fooflington** [philippe44/LMS-YouTube#46]
Currently getting `Plugins::YouTube::ProtocolHandler::__ANON__ (462) no stream/DASH found` for any item. It has previously been working wonderfully.

Platform:
- Ubuntu 22.04.3 LTS
- logitechmediaserver 8.3.1
- plugin 0.161

```
[23-08-24 17:51:24.1746] Plugins::YouTube::ProtocolHandler::__ANON__ (462) no stream/DASH found
```

Happy to provide further details if useful! Thanks!

**Comment by philippe44** [comment]
Please have a look on the LMS forum. Other users have seen this issue and have been able to find a workaround. I don't know what's happening as I can't reproduce on my side
