### ISSUE TITLE
cannot load player code - JS function 'gr' not found

### ISSUE THREAD

**Issue by beatz0001** [philippe44/LMS-YouTube#6]
After searching for a song in the webfrontend and click on play i get an error on my sqzeezebox 
radio:

cannot load player code:
Could not find JS function 'gr' at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/YouTube
/JSInterp.pm

and no audio output.

example (no playback):

URL: youtube://www.youtube.com/v/dipFMJckZOM
Titel: Vincent (Starry Starry Night) Don McLean 

on the other side some songs starts to play, I dont know where the difference is.

example (playback):

URL: youtube://www.youtube.com/v/K3JGxj2rvAs
Titel: Lykke Li (La Vie d'Adèle/La Vida de Adele) 

Thanks for updating the youtube plugin (its one of the best functions of the squeezebox)

**Comment by philippe44** [comment]
Solved in 0.37.4
