### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by downspot** [philippe44/LMS-YouTube#7]
Trying this out but all I get is the following:

Missing YouTube API key (see settings)

There is no location on the plugins page however for the settings.

**Comment by philippe44** [comment]
The settings are, like for all plugins, in LMS “settings”, tab “advanced”, then choose “youtube” in the dropdown list. Look at the thread here http://forums.slimdevices.com/showthread.php?105840-ANNOUNCE-YouTube-Plugin-(API-v3). Read the 1st post to see how to get an API key

From: Joel Flickinger 
Sent: Sunday, July 17, 2016 5:28 PM
To: philippe44/LMS-YouTube 
Subject: [philippe44/LMS-YouTube] settings (#7)

Trying this out but all I get is the following:

Missing YouTube API key (see settings)

There is no location on the plugins page however for the settings.

**Comment by downspot** [comment]
Ah there it is. Completely forgot about the advanced tab. Thank you!
