### ISSUE TITLE
Couldn't load Plugins::YouTube::Plugin

### ISSUE THREAD

**Issue by spinaternie** [philippe44/LMS-YouTube#8]
Loading plugin in Logitech Media Server Version: 7.9.0 - 1487144914 @ Wed Feb 15 08:11:18 UTC 2017 fails:

> Slim::bootstrap::tryModuleLoad (286) Warning: Module [Plugins::YouTube::Plugin] failed to load:
Base class package "IO::Socket::SSL" is empty.
    (Perhaps you need to 'use' the module which defines that package first,
    or make that module available in @INC (@INC contains: /var/lib/squeezeboxserver/cache/InstalledPlugins /usr/share/squeezeboxserver/CPAN/arch/5.20/arm-linux-gnueabihf-thread-multi-64int /usr/share/squeezeboxserver/CPAN/arch/5.20/arm-linux-gnueabihf-thread-multi-64int/auto /usr/share/squeezeboxserver/CPAN/arch/5.20.2/arm-linux-gnueabihf-thread-multi-64int /usr/share/squeezeboxserver/CPAN/arch/5.20.2/arm-linux-gnueabihf-thread-multi-64int/auto /usr/share/squeezeboxserver/CPAN/arch/5.20/arm-linux-gnueabihf-thread-multi-64int /usr/share/squeezeboxserver/CPAN/arch/5.20/arm-linux-gnueabihf-thread-multi-64int/auto /usr/share/squeezeboxserver/CPAN/arch/arm-linux-gnueabihf-thread-multi-64int /usr/share/squeezeboxserver/CPAN/arch/5.20 /usr/share/squeezeboxserver/lib /usr/share/squeezeboxserver/CPAN /usr/share/squeezeboxserver /usr/share/squeezeboxserver/CPAN /usr/share/squeezeboxserver /usr/sbin /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/arm-linux-gnueabihf/perl5/5.20 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .).
 at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/YouTube/ProtocolHandler.pm line 2.
BEGIN failed--compilation aborted at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/YouTube/ProtocolHandler.pm line 2.
Compilation failed in require at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/YouTube/Plugin.pm line 20.
BEGIN failed--compilation aborted at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/YouTube/Plugin.pm line 20.
Compilation failed in require at (eval 887) line 1.
BEGIN failed--compilation aborted at (eval 887) line 

> Logitech Media Server Version: 7.9.0 - 1487144914 @ Wed Feb 15 08:11:18 UTC 2017
Hostname: raspberrypi
IP-Adresse des Servers: 192.168.11.114
Server-HTTP-Portnummer: 9000
Betriebssystem: Debian - DE - utf8
Plattformarchitektur: armv7l-linux
Perl-Version: 5.20.2 - arm-linux-gnueabihf-thread-multi-64int
Audio::Scan: 0.95
Datenbankversion: DBD::SQLite 1.34_01 (sqlite 3.7.7.1)
Anzahl erkannter Player: 1

**Comment by philippe44** [comment]
Per log, the SSL installation, either the Perl wrapper or the base Linux piece, is missing in your system. I suggest you look in that direction. It's not linked with the plugin itself, but a missing part in the environment

**Comment by spinaternie** [comment]
Installing libio-socket-ssl-perl helped. Thanks for your support.
